### ISSUE TITLE
As a SounderSIPS users, i want to request timeseries transformations through a Unity DAPA endpoint

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-analytics-dapa#12]

**Comment by jjacob7734** [comment]
This is completed.  An example DAPA time series call is: `https://1gp9st60gd.execute-api.us-west-2.amazonaws.com/dev/am-uds-dapa/collections/JPL_MUR25-JPL-L4-GLOB-v04.2/processes/time-series:area?bbox=-77.0,35.0,-70.0,42.0&datetime=2022-01-01T00:00:00Z/2022-01-31T00:00:00Z`
