### ISSUE TITLE
Add health check endpoint for Process Mapper

### ISSUE THREAD

**Issue by jjacob7734** [unity-sds/unity-analytics-dapa#20]
Configure a Process Mapper endpoint that is suitable for a health check (runs quickly and returns 200 code) in the Unity SSM parameters.  The SSM endpoint format is `/unity/healthCheck/<MARKETPLACE_ITEM>/<COMPONENT_NAME>`. The SSM parameters should follow the Unity conventions described at https://app.gitbook.com/o/xZRqGQeQXJ0RP4VMj7Lq/s/UMIRhLdbRQTvMWop8Il9/developer-docs/common-services/docs/users-guide/deployment/deployment-concepts-and-infrastructure/unity-ssm-parameters

Acceptance Criteria:

- [x] A process mapper endpoint to be used for a health check returns within 10 seconds and returns 200 code
- [x] Process Mapper health check endpoint is added to the shared service SSM parameters during deployment.
- [x] Health check DAPA API endpoint configured (includes VPC Link linked to the Process Mapper load balancer)
- [x] Deploy DAPA process mapper health check to Unity-Dev
- [x] Deploy DAPA process mapper health check to Unity-Test
- [x] Deploy DAPA process mapper health check to Unity-Prod

**Comment by jjacob7734** [comment]
SSM endpoint could be `/unity/healthCheck/shared-services/process-mapper`

**Comment by jjacob7734** [comment]
**Status Update:**

- Added SSM parameters as a resource automated with Terraform: https://github.com/unity-sds/unity-analytics-dapa/blob/devel/terraform/ssm.tf
- Next steps:
    - Add `/health` endpoint to backend process mapper server
    - Expose `/health` endpoint through the ALB
    - Add health check API to API Gateway: `am-uds-dapa/processes/health`

**Comment by jjacob7734** [comment]
**Status Update:**

- Added health check endpoint to the backend process mapper service
- Modified load balancer to reflect the changes
- Next steps:
    - Add an API Gateway path for the new endpoint
    - Automate the health check endpoint deployment in Terraform

**Comment by jjacob7734** [comment]
**Status Update:**

- Terraform automation of process mapper health check is fully implemented, but not fully tested
- Currently using these SSM settings:
    `"Name": "/unity/healthCheck/shared-services/process-mapper/url"`
    `"Value": "https://p732jo04zi.execute-api.us-west-2.amazonaws.com/beta/am-uds-dapa/processes/health"`
- Deployment is not yet tested due to a permissions issue.  API deployment now requires `mcp-tenantOperator` role, which @zx128 does not have access to.
- Message from Gabe Ortiz on this: `Sadly, we did have to clean up APIG permissions as they were only half working and Tenants would not realize this until after deploying something.  This permission was moved out of Tenant Developer and only exists at the Tenant Operator level.  You can upgrade your permissions, by request Tenant SysAdmin in NAMS or have someone in the tenantOperator role deploy that for you.`
- Next step is for @zx128 to complete the SATERN training and acquire the mcp-tenantOperator role (expected completion at end of this week).  Afterwards he will test the deployment.

**Comment by GodwinShen** [comment]
@jjacob7734 ping for status update.

**Comment by jjacob7734** [comment]
**Status**

- @zx128 completed SATERN training required to get `mcp-TenantOperator` role.
- Just got this role added to his account on May 29.
- He will now use the new role to fully test the Process Mapper health check endpoint deployment automation and get it deployed to `Unity-Dev/Test/Prod` environments.

**Comment by jjacob7734** [comment]
**Status**

- Completed and deployed to `Unity-Dev/Test/Prod`
- Example: SSM configuration in `Unity-Prod` is `arn:aws:ssm:us-west-2:217910134673:parameter/unity/healthCheck/shared-services/process-mapper/url`
- Terraform code checked in: https://github.com/unity-sds/unity-analytics-dapa/blob/devel/terraform/ssm.tf, https://github.com/unity-sds/unity-analytics-dapa/blob/devel/terraform/ag_hc.tf
